export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME';
export const POSTGRES_HOST = 'POSTGRES_HOST';
export const POSTGRES_PORT = 'POSTGRES_PORT';
export const POSTGRES_USER = 'POSTGRES_USER';
export const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD';
export const POSTGRES_DB = 'POSTGRES_DB';
export const PORT = 'PORT';
